## Linear Algebra in python

In [1]:
import numpy as np

In [4]:
# coefficient matrix A
A = np.array([[3, 2], [1, -2]])
A

array([[ 3,  2],
       [ 1, -2]])

In [5]:
# constant matrix B
B = np.array([8 ,20])
B

array([ 8, 20])

In [8]:
 # Solve for x
x = np.linalg.solve(A,B) # solve for x 
x

array([ 7. , -6.5])