# Numpy Introduction 

In [3]:
# Import Library
import numpy as np

### What is an arry?
An array is a collection of elements of the same data type stored in contiguous memory locations. The elements in an array are accessed using an index or key, which is a numerical value that corresponds to the position of the element in the array. Arrays are a fundamental data structure in programming and are used to store and manipulate collections of data. 

In [4]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [5]:
a2 = a[np.newaxis , :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [6]:
a3 = a2[np.newaxis , :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Why do we have 1D , 2D , 3D arrays and where we need them in data science?

In data science, arrays are essential for organizing and manipulating data. The dimensions of arrays (1D, 2D, 3D, etc.) help structure data in ways that make analysis and computation easier. Here's an overview of each type and its uses:

### 1D Arrays
- **Definition**: A one-dimensional array is a simple list of values.
- **Example**:   `[1, 2, 3, 4, 5]`

- **Use Cases**:
- **Time Series Data**: Analyzing trends over time (e.g., stock prices).
- **Feature Vectors**: Representing a single observation's features in machine learning.

## 2D Arrays
- **Definition**: A two-dimensional array is like a table with rows and columns.
- **Example**: `[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]`

- **Use Cases**:
- **Matrices**: Representing data in a structured format, such as images (pixels in height x width format).
- **DataFrames**: Used in libraries like Pandas to handle tabular data, where rows represent observations and columns represent features.

## 3D Arrays
- **Definition**: A three-dimensional array can be thought of as a stack of matrices.
- **Example**: \
`[[[1, 2], [3, 4]],` \
`[[5, 6], [7, 8]]] `

- **Use Cases**:
- **Images and Videos**: Each frame of a video can be represented as a 2D array (height x width), and a sequence of frames as a 3D array (height x width x number of frames).
- **Multidimensional Data**: Analyzing data with multiple variables that interact, such as time, temperature, and location.

## Conclusion
Using different dimensional arrays allows data scientists to efficiently represent and manipulate data according to its structure. This flexibility is crucial for tasks such as data preprocessing, feature extraction, and model training in machine learning and deep learning.

## Creating arrays with numpy

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([(1,2,3,4,5) , (6,7,8,9,10)])
# 1D Array
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [22]:
# 2D Array
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

# Initialize arrays

In [23]:
zeros = np.zeros((3,6)) # (rows , columns)
print(zeros)
print(zeros.dtype)
print(type(zeros))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
float64
<class 'numpy.ndarray'>


In [24]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
full = np.full((4,4) , 6)
print(full)
print(full.dtype)
print(type(full))


[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
int64
<class 'numpy.ndarray'>


In [26]:
# Creating a identity matrix
identity = np.identity(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array Attributes

In [27]:
a.shape

(5,)

In [28]:
len(a)

5

In [29]:
a.ndim  # give us the dimension of the array

1

In [30]:
a.size  # numbers of elements in the array

5

## Basic data

In [31]:
a , b

(array([1, 2, 3, 4, 5]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [41]:
# Substraction 
substraction = a - b
substraction



array([[ 0,  0,  0,  0,  0],
       [-5, -5, -5, -5, -5]])

In [38]:
# Addition
# 1st way: using the '+' operator
addition = a + b
# 2nd way: using the 'add' method
addition1 = np.add(a,b)
print(addition1)
addition


[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [39]:
# Multiplication
multi = a * b
multi

array([[ 1,  4,  9, 16, 25],
       [ 6, 14, 24, 36, 50]])

In [ ]:
# Divison
div = a / b
print(div) 


[[1.         1.         1.         1.         1.        ]
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]]


array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]])

In [44]:
# Square of each element in the array
sqr = a ** b 
sqr

array([[      1,       4,      27,     256,    3125],
       [      1,     128,    6561,  262144, 9765625]])