# Numpy (Day-4)

## How to create an array from existing data

In [1]:
import numpy as np

In [9]:
data = np.arange(0,222,5)
print(data)
print('------------------------------------')
print(data.size)
print('-------')
print(len(data))

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
------------------------------------
45
-------
45


In [11]:
arr1 = data[40:45]
print(arr1)

[200 205 210 215 220]


In [16]:
a = [1,2,3,4,5,6,7]
b = [8,9,10,11,12,13,14]

In [ ]:
c = np.vstack((a,b)) # stack vertically 
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
d = np.hstack((a,b)) # Horizontally stack arrays a and b
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])